#! /usr/bin/env bash

# cc -c main.m
# cc main.o -framework Cocoa -o out
# rm -rf *.o

app_name='out'

if [[ $1 != '' ]]; then
	app_name=$1
fi

gcc main.m -framework Cocoa -o $app_name

rm -rf $app_name".app"

mkdir -p $app_name".app"/Contents/MacOS
mv $app_name $app_name".app"/Contents/MacOS
cp Info.plist $app_name".app"/Contents
